// REQ-BE-00033 / US8 — i18n bundle for the Shipper-side fake checkout. Stays a
// flat object so it can move into a real i18n library without rewrites.
export const paymentContent = {
    pay: {
        title: "Pagar envío",
        documentTitle: "Pagar envío · Truckr",
        lead: "Reservá tu envío con un pago seguro. Los datos de contacto del transportista se revelan al completar el pago.",
        requiredHint: "Todos los campos son obligatorios.",
        amountLabel: "Total a pagar",
        sectionCardTitle: "Tarjeta de crédito",
        sectionAddressTitle: "Dirección de facturación",
        fields: {
            cardNumber: { label: "Número de tarjeta", placeholder: "4242 4242 4242 4242" },
            expiry:     { label: "Vencimiento (MM/AA)", placeholder: "12/30" },
            cvv:        { label: "CVV", placeholder: "123" },
            holder:     { label: "Titular", placeholder: "Nombre y apellido" },
            street:     { label: "Calle y número", placeholder: "Av. Demo 1234" },
            city:       { label: "Ciudad", placeholder: "Buenos Aires" },
            province:   { label: "Provincia", placeholder: "Seleccioná una provincia" },
            postalCode: { label: "Código postal", placeholder: "1414" },
        },
        cta:         "Realizar pago",
        ctaLoading:  "Procesando…",
        cancelLabel: "Cancelar",
        cancelConfirm: {
            title: "¿Abandonás el pago?",
            text:  "El envío seguirá esperando tu pago, pero perderás los datos ingresados.",
            stay:  "Seguir pagando",
            leave: "Sí, abandonar",
        },
        errors: {
            generic:          "No pudimos procesar el pago. Intentá de nuevo.",
            cardRequired:     "Ingresá el número de tarjeta.",
            cardInvalid:      "El número de tarjeta no es válido.",
            expiryRequired:   "Ingresá el vencimiento.",
            expiryInvalid:    "Usá el formato MM/AA.",
            expiryPast:       "La tarjeta está vencida.",
            cvvRequired:      "Ingresá el CVV.",
            cvvInvalid:       "El CVV debe tener 3 dígitos.",
            holderRequired:   "Ingresá el titular de la tarjeta.",
            streetRequired:   "Ingresá la calle y el número.",
            cityRequired:     "Ingresá la ciudad.",
            provinceRequired: "Seleccioná una provincia.",
            postalRequired:   "Ingresá el código postal.",
            postalInvalid:    "El código postal no es válido.",
        },
    },
    success: {
        heading:        "Pago confirmado",
        documentTitle:  "Pago confirmado · Truckr",
        subheading:     "El transportista ya tiene tus datos y puede coordinar el retiro.",
        amountLabel:    "Pago acreditado",
        contactTitle:   "Datos de contacto del transportista",
        contactName:    "Nombre",
        contactEmail:   "Email",
        contactPhone:   "Teléfono",
        contactPhoneFallback: "No disponible",
        backCta:        "Volver a Mis Envíos",
    },
} as const;
