/* Prototype-stage i18n bundle for carrier pages. Mirrors the carve-out in
   landingContent.ts: content lives in a typed object until a real i18n
   library lands. UI components must read strings from here, never inline. */

export const carrierContent = {
    list: {
        title: "Mi flota",
        lead: "Gestioná los vehículos que ofrecés para nuevos viajes.",
        addCta: "Agregar vehículo",
        loadingLabel: "Cargando flota",
        loadError: "No pudimos cargar tu flota",
        retry: "Reintentar",
        emptyTitle: "Todavía no agregaste vehículos.",
        emptyCta: "Agregar el primero",
        gridLabel: "Vehículos de la flota",
        plate: "Patente",
        capacity: "Capacidad",
        capacityUnit: "kg",
        edit: "Editar",
        delete: "Eliminar",
        deleting: "Eliminando…",
        photoAlt: (label: string) => `Foto de ${label}`,
        placeholderEmoji: "🚚",
        pagination: {
            label: "Paginación de flota",
            previous: "← Anterior",
            next: "Siguiente →",
            page: (page: number, total: number) => `Página ${page} de ${total}`,
            count: (total: number) =>
                `${total} vehículo${total === 1 ? "" : "s"}`,
        },
        confirmDelete: {
            title: "Eliminar vehículo",
            text: "Esta acción no se puede deshacer. ¿Querés continuar?",
            cancel: "Cancelar",
            confirm: "Eliminar",
        },
    },
    form: {
        editTitle: "Editar vehículo",
        newTitle: "Agregar vehículo",
        primaryTitle: "Mi vehículo",
        lead: "Completá los datos básicos. Las fotos ayudan a que los expedidores te elijan más rápido.",
        hydrating: "Cargando datos del vehículo",
        saveError: "No pudimos guardar el vehículo.",
        plateHint:
            "Patente esperada: AA123BB o AAA123 (6-8 caracteres alfanuméricos).",
        volumeLabel: (cm3: string) => `Volumen estimado: ${cm3} cm³`,
        fields: {
            make: "Marca",
            model: "Modelo",
            year: "Año",
            plate: "Patente",
            vehicleType: "Tipo de vehículo",
            maxLoadKg: "Capacidad de carga (kg)",
            dimensions: "Dimensiones interiores",
            length: "Largo (cm)",
            width: "Ancho (cm)",
            height: "Alto (cm)",
            description: "Descripción (opcional)",
            gps: "Tiene GPS / trackeo activo",
        },
        submit: {
            saving: "Guardando…",
            create: "Agregar vehículo",
            update: "Guardar cambios",
            cancel: "Cancelar",
        },
        existingPhotosTitle: "Fotos cargadas",
        existingPhotosCount: (kept: number, max: number) => `${kept} de ${max}`,
        existingPhotoRemove: "Quitar",
        existingPhotoUndo: "Restaurar",
        existingPhotoMarked: "Se eliminará",
        existingPhotoRemoveAria: (label: string) => `Quitar ${label}`,
        existingPhotoUndoAria: (label: string) => `Restaurar ${label}`,
        existingPhotosPending: (n: number) =>
            `${n} foto${n === 1 ? "" : "s"} se va${n === 1 ? "" : "n"} a eliminar al guardar.`,
        photoAlt: (label: string) => `Foto de ${label || "vehículo"}`,
    },
    uploader: {
        defaultLabel: "Subir fotos",
        accept: "JPG, PNG o WebP",
        max: (n: number) => `máx. ${n}`,
        limitReached: (n: number) => `Llegaste al límite (${n} fotos).`,
        rejected: "Formato no soportado. Usá JPG, PNG o WebP.",
        active: "Soltá las fotos para subirlas.",
        prompt: (n: number) =>
            `Arrastrá hasta ${n} foto${n === 1 ? "" : "s"} o hacé clic para elegir.`,
        gridLabel: "Fotos seleccionadas",
        remove: "Quitar",
        removeFile: (name: string) => `Quitar ${name}`,
    },
    vehicleTypes: {
        van: "Van / Utilitario",
        truck_small: "Camión chico",
        truck_large: "Camión grande",
        semi_trailer: "Semirremolque",
    } as Record<string, string>,
    availability: {
        list: {
            title: "Mi disponibilidad",
            lead: "Publicá las ventanas de tiempo y zonas en las que podés operar.",
            addCta: "Publicar disponibilidad",
            loadingLabel: "Cargando disponibilidad",
            loadError: "No pudimos cargar tus ventanas de disponibilidad",
            retry: "Reintentar",
            emptyTitle: "Todavía no tenés ventanas publicadas",
            emptyLead: "Publicá una ventana para que los expedidores te encuentren: elegí tu vehículo, las zonas de origen y destino, el período y el precio por km.",
            emptyCta: "Publicar la primera",
            gridLabel: "Ventanas de disponibilidad",
            origin: "Origen",
            destination: "Destino",
            destinationAny: "Destino abierto",
            pricePerKm: "Precio/km",
            maxKm: "Máx. km",
            from: "Desde",
            to: "Hasta",
            active: "Visible",
            inactive: "Oculta",
            activeTitle: "Visible para expedidores que buscan en tu ruta.",
            inactiveTitle: "Oculta — no aparece en búsquedas de expedidores.",
            deactivate: "Ocultar",
            reactivate: "Mostrar",
            toggling: "Actualizando…",
            edit: "Editar",
            delete: "Eliminar",
            deleteTitle: "Eliminar disponibilidad",
            deleteConfirm: "La ventana se quitará de tu lista. Tenés unos segundos para deshacer.",
            deleteFailed: "No se pudo eliminar la ventana. La lista se actualizó.",
            deleteBlocked: "Esta ventana tiene ofertas de carga asociadas y no puede eliminarse.",
            deleteBlockedTitle: "No se puede eliminar",
            deleteBlockedBody: "Esta ventana tiene ofertas de carga activas o pendientes. Para poder eliminarla, primero tienen que cerrarse todas las ofertas asociadas.",
            deleteBlockedClose: "Entendido",
            deleting: "Eliminando…",
            deleteCancel: "Cancelar",
            savedBanner: "Ventana guardada.",
            savedBannerNew: "Ventana publicada. Los expedidores ya pueden encontrarte en esta ruta.",
            savedBannerDismiss: "Cerrar",
            deletedBanner: "Ventana eliminada.",
            undoCta: "Deshacer",
            undoDeactivateAria: "Deshacer: reactivar ventana ocultada",
            undoDeleteAria: "Deshacer: cancelar eliminación",
            toggledHidden: "Ventana ocultada.",
            toggledVisible: "Ventana visible ahora.",
            pagination: {
                label: "Paginación de disponibilidad",
                previous: "Anterior",
                next: "Siguiente",
                page: (page: number, total: number) => `Página ${page} de ${total}`,
                count: (total: number) => `${total} ventana${total === 1 ? "" : "s"}`,
            },
        },
        form: {
            newTitle: "Nueva disponibilidad",
            editTitle: "Editar disponibilidad",
            lead: "Definí la zona de origen y destino, el precio y el período en que estás disponible.",
            hydrating: "Cargando datos de disponibilidad",
            saveError: "No pudimos guardar. Revisá los campos marcados e intentá de nuevo.",
            vehicleRequired: "Seleccioná un vehículo para continuar.",
            noVehiclesAlert: "Primero necesitás agregar un vehículo para publicar disponibilidad.",
            noVehiclesCta: "Agregar vehículo →",
            requiredLegend: "Obligatorio",
            originLegend: "Origen",
            destinationLegend: "Destino (opcional)",
            periodLegend: "Período",
            fields: {
                vehicle: "Vehículo",
                originProvince: "Provincia",
                originLocality: "Localidad (opcional)",
                originLocalityHelp: "Especificá la ciudad o localidad si querés ser más preciso.",
                destinationProvince: "Provincia (opcional)",
                destinationProvinceHelp: "Dejá vacío si aceptás cargas a cualquier destino.",
                destinationLocality: "Localidad (opcional)",
                destinationLocalityHelp: "Completá solo si indicaste provincia de destino.",
                pricePerKm: "Precio por km ($)",
                pricePerKmHelp: "En pesos argentinos. Usá punto decimal: 850.50",
                pricePerKmInvalid: "Ingresá un precio válido mayor que cero.",
                maxKm: "Kilómetros máximos",
                maxKmInvalid: "Ingresá una distancia válida (número entero mayor que cero).",
                availableFrom: "Disponible desde",
                availableTo: "Disponible hasta",
                availableFromHelp: "Fecha en que empezás a estar disponible.",
                availableToHelp: "Debe ser posterior o igual a la fecha de inicio.",
                maxKmHelp: "Distancia máxima del viaje (ida).",
            },
            submit: {
                saving: "Guardando…",
                create: "Publicar disponibilidad",
                update: "Guardar cambios",
                cancel: "Cancelar",
            },
        },
    },
} as const;

export function vehicleTypeLabel(value: string): string {
    return carrierContent.vehicleTypes[value] ?? value.replace(/_/g, " ");
}
