export const offersAndShipmentsContent = {
    inbox: {
        title: "Ofertas recibidas",
        lead: "Revisá las ofertas pendientes sobre tus ventanas y decidí si aceptarlas o rechazarlas.",
        filterLabel: "Estado",
        statusOptions: {
            pending: "Pendientes",
            accepted: "Aceptadas",
            paid: "Pagadas",
            rejected: "Rechazadas",
            expired: "Vencidas",
            cancelled: "Canceladas",
        },
        loadingLabel: "Cargando ofertas recibidas",
        loadError: "No pudimos cargar tus ofertas recibidas",
        retry: "Reintentar",
        emptyTitle: "No hay ofertas en este estado",
        emptyLead: "Cuando un expedidor te envíe una oferta sobre una ventana activa, va a aparecer acá.",
        amount: "Oferta",
        expiresAt: "Vence",
        shipper: "Expedidor",
        cargoRouteFallback: (id: number) => `Carga #${id}`,
        detailsOpen: "Ver detalle",
        detailTitle: "Detalle de la carga",
        pickupAddress: "Retiro",
        deliveryAddress: "Entrega",
        pickupWindow: "Ventana de retiro",
        weight: "Peso",
        volume: "Volumen",
        declaredValue: "Valor declarado",
        description: "Descripción",
        windowTitle: "Ventana propuesta",
        windowDate: "Disponibilidad",
        windowRate: "Tarifa",
        windowMaxKm: "Máx. km",
        accept: "Aceptar",
        reject: "Rechazar",
        processing: "Procesando…",
        confirm: {
            title: "Confirmar acción",
            acceptText: "Si aceptás esta oferta, las demás ofertas pendientes de la misma carga se rechazarán automáticamente.",
            rejectText: "Si rechazás esta oferta, tu ventana vuelve a quedar disponible en el marketplace.",
            cancel: "Cancelar",
            accept: "Confirmar aceptación",
            reject: "Confirmar rechazo",
        },
        successAccepted: "Oferta aceptada. El viaje ya figura en tus viajes.",
        successRejected: "Oferta rechazada. La ventana volvió a quedar disponible.",
        pagination: {
            label: "Paginación de ofertas",
            previous: "Anterior",
            next: "Siguiente",
            page: (page: number, total: number) => `Página ${page} de ${total}`,
            count: (total: number) => `${total} oferta${total === 1 ? "" : "s"}`,
        },
    },
    shipments: {
        title: "Mis viajes",
        lead: "Seguí tus viajes activos y consultá su estado histórico.",
        loadingLabel: "Cargando viajes",
        loadError: "No pudimos cargar tus viajes",
        retry: "Reintentar",
        statusLabel: "Filtro de viaje",
        statuses: {
            all: "Todos",
            pending_payment: "Pendiente de pago",
            to_pick_up: "A recoger",
            in_transit: "En tránsito",
            delivered: "Entregados",
        },
        shipmentId: (id: number) => `Viaje #${id}`,
        cargoOfferId: (id: number) => `Oferta #${id}`,
        emptyTitle: "No hay viajes para este filtro",
        emptyLead: "Cuando aceptes una oferta desde la bandeja, vas a ver los viajes acá.",
        acceptedAt: "Pendiente de pago desde",
        pickedUpAt: "A recoger desde",
        deliveredAt: "Entregado",
        statusBadge: {
            pending_payment: "Pendiente de pago",
            to_pick_up: "A recoger",
            in_transit: "En tránsito",
            delivered: "Entregado",
        } as Record<string, string>,
        pagination: {
            label: "Paginación de viajes",
            previous: "Anterior",
            next: "Siguiente",
            page: (page: number, total: number) => `Página ${page} de ${total}`,
            count: (total: number) => `${total} viaje${total === 1 ? "" : "s"}`,
        },
    },
    header: {
        inboxLink: "Bandeja",
        pendingBadge: (count: number) => `${count} pendiente${count === 1 ? "" : "s"}`,
        pendingBadgeAria: (count: number) => `Tenés ${count} oferta${count === 1 ? "" : "s"} pendiente${count === 1 ? "" : "s"}`,
    },
} as const;
