export const carrierSearchContent = {
    title: "Buscar transportistas",
    lead: "Encontrá transportistas por zona de origen, destino y fechas de retiro.",
    form: {
        origin: "Zona de origen",
        destination: "Zona de destino",
        dateFrom: "Retiro desde",
        dateTo: "Retiro hasta",
        submit: "Buscar",
        submitBusy: "Buscando...",
        originPlaceholder: "Ej: CABA, Rosario, Mendoza",
        destinationPlaceholder: "Ej: Córdoba, Tucumán",
        rangeError: "La fecha hasta debe ser igual o posterior a la fecha desde.",
        filterLegend: "Criterios de búsqueda de transportistas",
    },
    states: {
        idleTitle: "Completá los filtros para empezar",
        idleText: "Usamos coincidencia flexible por zona y ventanas activas por fecha.",
        loading: "Buscando transportistas disponibles...",
        loadingLabel: "Cargando transportistas",
        emptyTitle: "No encontramos resultados",
        emptyText: "Probá ampliar el rango de fechas o usar otra combinación de zonas.",
        errorTitle: "No pudimos completar la búsqueda",
        retry: "Reintentar",
    },
    card: {
        zones: "Ruta",
        price: "Desde",
        priceUnit: "por km",
        available: "Disponible",
        base: "Base",
        rating: "Rating",
        shipments: "viajes completados",
        details: "Ver detalle",
        nameFallback: "Transportista sin nombre",
    },
    resultsLabel: "Resultados de búsqueda de transportistas",
} as const;
